# Generated by Django 4.1.7 on 2023-04-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='tikiapp.category'),
        ),
    ]
