# Generated by Django 4.1.7 on 2023-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
