# Generated by Django 4.1.7 on 2023-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='Account/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m'),
        ),
    ]
