# Generated by Django 4.1.7 on 2023-04-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0002_remove_account_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
