# Generated by Django 4.1.7 on 2023-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0002_remove_seller_image_account_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='Category/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='Product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='image',
            field=models.ImageField(default=None, upload_to='Product/%Y/%m'),
        ),
    ]
