# Generated by Django 4.1.7 on 2023-04-08 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ManyToManyField(related_name='evaluate_set', through='tikiapp.Evaluate', to=settings.AUTH_USER_MODEL),
        ),
    ]
