# Generated by Django 4.1.7 on 2023-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0003_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='Category/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='Product/%Y/%m'),
        ),
    ]
