# Generated by Django 4.1.7 on 2023-04-08 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0004_alter_evaluate_rate_alter_product_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='account',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='evaluate', to=settings.AUTH_USER_MODEL),
        ),
    ]
