# Generated by Django 4.1.7 on 2023-04-09 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0005_alter_evaluate_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evaluate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
