# Generated by Django 4.1.7 on 2023-04-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikiapp', '0007_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_seller_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
